-- Fantasy Jupiler Pro League: centrale accounts, teams, data, scores en deadlines.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Manager' check (char_length(display_name) between 1 and 28),
  created_at timestamptz not null default now()
);

create table if not exists public.players (
  id text primary key,
  provider_player_id bigint unique,
  name text not null,
  club_id bigint,
  club_name text not null,
  position text not null check (position in ('GK','DEF','MID','FWD')),
  minutes integer not null default 0 check (minutes >= 0),
  price numeric(5,1) not null check (price > 0),
  total_points numeric(10,2) not null default 0,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.gameweeks (
  id bigint generated by default as identity primary key,
  season integer not null,
  number integer not null check (number > 0),
  name text not null,
  lock_at timestamptz not null,
  status text not null default 'upcoming' check (status in ('upcoming','active','finished')),
  unique(season,number)
);

create table if not exists public.fixtures (
  id bigint primary key,
  gameweek_id bigint not null references public.gameweeks(id) on delete cascade,
  kickoff timestamptz not null,
  status text not null,
  home_team text not null,
  away_team text not null,
  home_score integer,
  away_score integer,
  stats_processed boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.player_match_stats (
  fixture_id bigint not null references public.fixtures(id) on delete cascade,
  player_id text not null references public.players(id) on delete cascade,
  minutes integer not null default 0,
  stats jsonb not null default '{}'::jsonb,
  fantasy_points numeric(10,2) not null default 0,
  updated_at timestamptz not null default now(),
  primary key(fixture_id,player_id)
);

create table if not exists public.teams (
  user_id uuid primary key references auth.users(id) on delete cascade,
  team_name text not null default 'Mijn Fantasy Team' check (char_length(team_name) between 1 and 28),
  squad_ids text[] not null default '{}',
  bench_gk_id text,
  bench_outfield_id text,
  budget numeric(5,1) not null default 100.0,
  total_points numeric(10,2) not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.gameweek_lineups (
  gameweek_id bigint not null references public.gameweeks(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  squad_ids text[] not null,
  starter_ids text[] not null,
  bench_gk_id text not null,
  bench_outfield_id text not null,
  locked_at timestamptz not null default now(),
  primary key(gameweek_id,user_id)
);

create table if not exists public.gameweek_scores (
  gameweek_id bigint not null references public.gameweeks(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  points numeric(10,2) not null default 0,
  breakdown jsonb not null default '{}'::jsonb,
  calculated_at timestamptz not null default now(),
  primary key(gameweek_id,user_id)
);

create index if not exists fixtures_gameweek_idx on public.fixtures(gameweek_id,kickoff);
create index if not exists player_match_stats_player_idx on public.player_match_stats(player_id);
create index if not exists gameweeks_lock_idx on public.gameweeks(status,lock_at);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles(id,display_name)
  values(new.id,coalesce(nullif(new.raw_user_meta_data->>'display_name',''),'Manager'))
  on conflict(id) do nothing;
  insert into public.teams(user_id) values(new.id) on conflict(user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Bestaande Auth-gebruikers krijgen bij een herhaalde migratie ook een profiel/team.
insert into public.profiles(id,display_name)
select id,coalesce(nullif(raw_user_meta_data->>'display_name',''),'Manager') from auth.users
on conflict(id) do nothing;
insert into public.teams(user_id) select id from auth.users on conflict(user_id) do nothing;

alter table public.profiles enable row level security;
alter table public.players enable row level security;
alter table public.gameweeks enable row level security;
alter table public.fixtures enable row level security;
alter table public.player_match_stats enable row level security;
alter table public.teams enable row level security;
alter table public.gameweek_lineups enable row level security;
alter table public.gameweek_scores enable row level security;

drop policy if exists "profiles own read" on public.profiles;
create policy "profiles own read" on public.profiles for select using (auth.uid() = id);
drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
drop policy if exists "players public read" on public.players;
create policy "players public read" on public.players for select using (true);
drop policy if exists "gameweeks public read" on public.gameweeks;
create policy "gameweeks public read" on public.gameweeks for select using (true);
drop policy if exists "fixtures public read" on public.fixtures;
create policy "fixtures public read" on public.fixtures for select using (true);
drop policy if exists "stats public read" on public.player_match_stats;
create policy "stats public read" on public.player_match_stats for select using (true);
drop policy if exists "teams own read" on public.teams;
create policy "teams own read" on public.teams for select using (auth.uid() = user_id);
drop policy if exists "lineups own read" on public.gameweek_lineups;
create policy "lineups own read" on public.gameweek_lineups for select using (auth.uid() = user_id);
drop policy if exists "scores public read" on public.gameweek_scores;
create policy "scores public read" on public.gameweek_scores for select using (true);

create or replace view public.leaderboard as
select user_id as manager_id,team_name,total_points
from public.teams;
grant select on public.leaderboard to anon,authenticated;

create or replace function public.current_edit_window()
returns table(gameweek_id bigint,gameweek_number integer,lock_at timestamptz,status text,locked boolean)
language sql
stable
security definer set search_path = public
as $$
  select g.id,g.number,g.lock_at,g.status,
    (g.status = 'active' or (g.status <> 'finished' and now() >= g.lock_at)) as locked
  from public.gameweeks g
  where g.status in ('active','upcoming')
  order by case when g.status = 'active' then 0 else 1 end,g.lock_at
  limit 1;
$$;
grant execute on function public.current_edit_window() to anon,authenticated;

create or replace function public.save_my_team(
  p_name text,
  p_squad_ids text[],
  p_bench_gk_id text default null,
  p_bench_outfield_id text default null
)
returns table(saved boolean,locked boolean,lock_at timestamptz,gameweek_number integer)
language plpgsql
security definer set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_count integer := coalesce(cardinality(p_squad_ids),0);
  v_distinct integer;
  v_found integer;
  v_gk integer;
  v_def integer;
  v_mid integer;
  v_fwd integer;
  v_spent numeric(8,1);
  v_window record;
begin
  if v_user is null then raise exception 'Log eerst in.'; end if;
  select * into v_window from public.current_edit_window();
  if found and v_window.locked then
    raise exception 'De opstelling is vergrendeld: speeldag % is begonnen.',v_window.gameweek_number;
  end if;
  if char_length(trim(coalesce(p_name,''))) not between 1 and 28 then
    raise exception 'De teamnaam moet 1 tot 28 tekens bevatten.';
  end if;
  if v_count > 8 then raise exception 'Een selectie mag maximaal 8 spelers bevatten.'; end if;

  select count(distinct x) into v_distinct from unnest(coalesce(p_squad_ids,'{}')) x;
  if v_distinct <> v_count then raise exception 'Een speler kan maar één keer in je selectie staan.'; end if;

  select count(*),coalesce(sum(price),0),
    count(*) filter(where position='GK'),count(*) filter(where position='DEF'),
    count(*) filter(where position='MID'),count(*) filter(where position='FWD')
  into v_found,v_spent,v_gk,v_def,v_mid,v_fwd
  from public.players where active and id = any(coalesce(p_squad_ids,'{}'));

  if v_found <> v_count then raise exception 'De selectie bevat een onbekende of inactieve speler.'; end if;
  if v_spent > 100 then raise exception 'Onvoldoende budget: je selectie kost €%M.',v_spent; end if;
  if v_gk > 2 or v_def > 2 or v_mid > 2 or v_fwd > 2 then
    raise exception 'Je mag maximaal 2 spelers per positie kiezen.';
  end if;

  if v_count = 8 then
    if not (v_gk=2 and v_def=2 and v_mid=2 and v_fwd=2) then
      raise exception 'Een volledige selectie vereist exact 2 GK, 2 DEF, 2 MID en 2 FWD.';
    end if;
    if p_bench_gk_id is not null and not exists(select 1 from public.players where id=p_bench_gk_id and position='GK' and id=any(p_squad_ids)) then
      raise exception 'De reservekeeper is ongeldig.';
    end if;
    if p_bench_outfield_id is not null and not exists(select 1 from public.players where id=p_bench_outfield_id and position<>'GK' and id=any(p_squad_ids)) then
      raise exception 'De veldspeler op de bank is ongeldig.';
    end if;
  elsif p_bench_gk_id is not null or p_bench_outfield_id is not null then
    raise exception 'Kies pas bankspelers nadat je selectie volledig is.';
  end if;

  insert into public.teams(user_id,team_name,squad_ids,bench_gk_id,bench_outfield_id,budget,updated_at)
  values(v_user,trim(p_name),coalesce(p_squad_ids,'{}'),p_bench_gk_id,p_bench_outfield_id,100-v_spent,now())
  on conflict(user_id) do update set
    team_name=excluded.team_name,squad_ids=excluded.squad_ids,
    bench_gk_id=excluded.bench_gk_id,bench_outfield_id=excluded.bench_outfield_id,
    budget=excluded.budget,updated_at=now();

  return query select true,coalesce(v_window.locked,false),v_window.lock_at,v_window.gameweek_number;
end;
$$;
grant execute on function public.save_my_team(text,text[],text,text) to authenticated;

create or replace function public.lock_gameweek(p_gameweek_id bigint)
returns integer
language plpgsql
security definer set search_path = public
as $$
declare v_inserted integer;
begin
  insert into public.gameweek_lineups(gameweek_id,user_id,squad_ids,starter_ids,bench_gk_id,bench_outfield_id)
  select p_gameweek_id,t.user_id,t.squad_ids,
    (select array_agg(u.id order by u.ord) from unnest(t.squad_ids) with ordinality u(id,ord)
      where u.id not in (t.bench_gk_id,t.bench_outfield_id)),
    t.bench_gk_id,t.bench_outfield_id
  from public.teams t
  where cardinality(t.squad_ids)=8 and t.bench_gk_id is not null and t.bench_outfield_id is not null
  on conflict(gameweek_id,user_id) do nothing;
  get diagnostics v_inserted = row_count;
  update public.gameweeks set status='active' where id=p_gameweek_id and status='upcoming';
  return v_inserted;
end;
$$;
revoke all on function public.lock_gameweek(bigint) from public,anon,authenticated;
grant execute on function public.lock_gameweek(bigint) to service_role;

create or replace function public.recalculate_gameweek_scores(p_gameweek_id bigint)
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  with totals as (
    select s.player_id,sum(s.minutes)::integer as minutes,sum(s.fantasy_points)::numeric(10,2) as points
    from public.player_match_stats s join public.fixtures f on f.id=s.fixture_id
    where f.gameweek_id=p_gameweek_id group by s.player_id
  ), calculated as (
    select l.user_id,
      coalesce((select sum(coalesce(t.points,0)) from unnest(l.starter_ids) sid
        left join totals t on t.player_id=sid where coalesce(t.minutes,0)>0),0)
      + case when exists(
          select 1 from unnest(l.starter_ids) sid join public.players p on p.id=sid
          left join totals t on t.player_id=sid where p.position='GK' and coalesce(t.minutes,0)=0
        ) then coalesce((select t.points from totals t where t.player_id=l.bench_gk_id and t.minutes>0),0) else 0 end
      + case when exists(
          select 1 from unnest(l.starter_ids) sid join public.players p on p.id=sid
          left join totals t on t.player_id=sid where p.position<>'GK' and coalesce(t.minutes,0)=0
        ) then coalesce((select t.points from totals t where t.player_id=l.bench_outfield_id and t.minutes>0),0) else 0 end
      as points
    from public.gameweek_lineups l where l.gameweek_id=p_gameweek_id
  )
  insert into public.gameweek_scores(gameweek_id,user_id,points,breakdown,calculated_at)
  select p_gameweek_id,user_id,points,jsonb_build_object('automatic_substitutions',true),now() from calculated
  on conflict(gameweek_id,user_id) do update set points=excluded.points,breakdown=excluded.breakdown,calculated_at=now();

  update public.teams t set total_points=coalesce(x.points,0)
  from (select user_id,sum(points) points from public.gameweek_scores group by user_id) x
  where t.user_id=x.user_id;
end;
$$;
revoke all on function public.recalculate_gameweek_scores(bigint) from public,anon,authenticated;
grant execute on function public.recalculate_gameweek_scores(bigint) to service_role;

create or replace function public.refresh_player_totals()
returns void
language sql
security definer set search_path = public
as $$
  update public.players p set
    total_points=coalesce(x.points,0),
    updated_at=now()
  from (
    select p2.id,coalesce(sum(s.fantasy_points),0)::numeric(10,2) as points
    from public.players p2 left join public.player_match_stats s on s.player_id=p2.id
    group by p2.id
  ) x
  where p.id=x.id;
$$;
revoke all on function public.refresh_player_totals() from public,anon,authenticated;
grant execute on function public.refresh_player_totals() to service_role;
